spring:
  application:
    name: courierflow
  datasource:
    url: jdbc:postgresql://localhost:5432/courierflow_db
    username: courierflow_user
    password: courierflow_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
